package pl.edu.pk.kron.visualcommunicator.common.model;

public enum MessageType {
    CLIENT_GET_AUTH,
    CLIENT_GET_AUTH_TOKEN,
    CLIENT_GET_CONVERSATIONS,
    CLIENT_GET_MESSAGES,
    CLIENT_SEND_MESSAGE,
    CLIENT_CREATE_NEW_CONVERSATION,
    CLIENT_WHO_AM_I,
    CLIENT_GET_USERNAME_OF_USERID,
    CLIENT_GET_AVAILABLE_MESSAGE_RECIPIENTS,
    CLIENT_GET_USERS_BY_ID_OR_PART_OF_NAME,
    CLIENT_ADMIN_CREATE_NEW_USER,

    SERVER_NEW_MESSAGE,
    SERVER_NEW_CONVERSATION,
    SERVER_ERR
}
